kind: pipeline
name: default

steps:
- name: update certificate
  image: plugins/ansible:3
  environment:
    ANSIBLE_CONFIG: ansible.cfg
  settings:
    playbook: update_certificate.yaml
    inventory: inventory/prod/hosts
    private_key:
      from_secret: ansible_private_key
    vault_password:
      from_secret: ansible_vault_password

trigger:
  branch:
  - development
  - stable
  event:
  - push
  - tag
