kind: pipeline
name: default

steps:
  - name: update certificate
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      SUPER_USER:
        from_secret: super_user
      SUPER_PASS:
        from_secret: super_pass
    settings:
      playbook: .ansible/update_certificate.yaml
      inventory: .ansible/inventories/production.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  branch:
    - stable
  event:
    - push
