kind: pipeline
name: default

steps:
  - name: update certificate
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      playbook: .ansible/update_certificate.yaml
      inventory: .ansible/inventory/production/hosts
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  branch:
    - stable
  event:
    - push
