# ansible-playbook update_certificate.yaml -i inventory/production/hosts --vault-id ~/.tokens/master_id

- hosts: all
  gather_facts: no
  pre_tasks:

  - name: Create new *.pem files
    raw: >
      touch /jffs/.cert/cert.pem && 
      touch /jffs/.cert/key.pem

  - name: Write public certificate data
    raw: echo '{{ cert }}' > /jffs/.cert/cert.pem

  - name: Write private key data
    raw: echo '{{ key }}' > /jffs/.cert/key.pem

  - name: Restart http server
    raw: service restart_httpd
